#!/usr/bin/env python3
"""
CHANGELOG automation script.

Reads git log, parses conventional commits, and outputs Keep a Changelog
formatted entries. Designed to be run manually or via CI/release workflow.

Usage:
    python3 scripts/generate_changelog.py                    # all commits since last tag
    python3 scripts/generate_changelog.py --since v0.0.0     # since specific tag
    python3 scripts/generate_changelog.py --from <commit>     # from specific commit
    python3 scripts/generate_changelog.py --dry-run          # show to stdout, don't write
"""

import argparse
import subprocess
import re
from datetime import datetime, date
from pathlib import Path
from typing import Optional

# Conventional commit types → Keep a Changelog categories
TYPE_TO_CATEGORY = {
    "feat": "Added",
    "fix": "Fixed",
    "docs": "Changed",
    "style": "Changed",
    "refactor": "Changed",
    "test": "Changed",
    "chore": "Changed",
    "ci": "Changed",
    "perf": "Changed",
    "revert": "Changed",
}

# Categories in desired order
CATEGORIES = ["Added", "Changed", "Fixed", "Removed", "Deprecated", "Security"]


def run_git(args: list[str]) -> str:
    result = subprocess.run(
        ["git"] + args,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def parse_conventional_commit(message: str) -> Optional[dict]:
    """
    Parse a conventional commit message.
    
    Format: <type>(<scope>): <description>
    Examples:
      - feat(cli): add new command
      - fix(api): resolve race condition
      - docs: update README
    """
    pattern = r'^(\w+)(?:\([\w-]+\))?!?:\s+(.+)$'
    match = re.match(pattern, message.strip())
    if not match:
        return None
    
    commit_type = match.group(1).lower()
    description = match.group(2).strip()
    
    # Map to changelog category
    category = TYPE_TO_CATEGORY.get(commit_type, "Changed")
    
    return {
        "type": commit_type,
        "category": category,
        "description": description,
        "breaking": "!" in message or "BREAKING" in message,
    }


def get_git_log(since: Optional[str] = None, until: Optional[str] = None) -> list[dict]:
    """Get git log as list of commit dicts."""
    args = ["log", "--format=%H|%s", "--no-merges"]
    
    if since:
        args.append(f"{since}..HEAD")
    elif until:
        args.append(f"--until={until}")
    
    output = run_git(args)
    if not output:
        return []
    
    commits = []
    for line in output.split("\n"):
        if not line:
            continue
        parts = line.split("|", 1)
        if len(parts) != 2:
            continue
        
        sha = parts[0]
        message = parts[1]
        parsed = parse_conventional_commit(message)
        if parsed:
            parsed["sha"] = sha[:7]
            commits.append(parsed)
    
    return commits


def format_category_entries(category: str, entries: list[dict]) -> str:
    """Format a category with its entries in Keep a Changelog format."""
    if not entries:
        return ""
    
    lines = [f"### {category}", ""]
    for entry in entries:
        scope = f"({entry['type']})" if entry["type"] != "chore" else ""
        breaking = " **BREAKING**" if entry["breaking"] else ""
        lines.append(f"- **{entry['description']}**{breaking} `{entry['sha']}`")
    
    lines.append("")
    return "\n".join(lines)


def generate_changelog(commits: list[dict], output_path: Optional[Path] = None, dry_run: bool = False) -> str:
    """Generate CHANGELOG entry from commits."""
    today = date.today().isoformat()
    
    # Group by category
    by_category: dict[str, list[dict]] = {cat: [] for cat in CATEGORIES}
    for commit in commits:
        cat = commit["category"]
        if cat in by_category:
            by_category[cat].append(commit)
    
    # Build output
    sections = []
    sections.append("## [Unreleased]")
    sections.append("")
    sections.append(f"### Added (auto-generated {today})")
    sections.append("")
    sections.append("*Auto-generated by scripts/generate_changelog.py*")
    sections.append("")
    
    # Process each category
    for category in CATEGORIES:
        entries = by_category[category]
        if entries:
            sections.append(f"### {category}")
            sections.append("")
            for entry in entries:
                scope = f"({entry['type']})" if entry["type"] != "chore" else ""
                breaking = " **BREAKING**" if entry["breaking"] else ""
                desc = entry["description"]
                sha = entry["sha"]
                sections.append(f"- {desc}{breaking} {scope}`{sha}`")
            sections.append("")
    
    output = "\n".join(sections)
    
    if dry_run:
        print(output)
        return output
    
    if output_path:
        output_path.write_text(output)
        print(f"Written: {output_path}")
    
    return output


def main():
    parser = argparse.ArgumentParser(description="Generate CHANGELOG entries from conventional commits")
    parser.add_argument("--since", help="Generate commits since this tag/commit")
    parser.add_argument("--from", dest="from_commit", help="Generate commits from this commit")
    parser.add_argument("--dry-run", action="store_true", help="Print to stdout instead of writing")
    parser.add_argument("--output", type=Path, help="Output file path")
    
    args = parser.parse_args()
    
    since = args.since or getattr(args, "from_commit", None)
    
    # Get current version from latest tag
    try:
        last_tag = run_git(["describe", "--tags", "--abbrev=0"])
    except subprocess.CalledProcessError:
        last_tag = None
    
    commits = get_git_log(since=since or last_tag)
    
    if not commits:
        print("No commits found")
        return
    
    print(f"Found {len(commits)} conventional commits")
    for c in commits:
        print(f"  [{c['category']}] {c['description']} ({c['sha']})")
    
    generate_changelog(commits, output_path=args.output, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
